### ISSUE TITLE
Add docstrings and documentation with Documenter.jl

### ISSUE THREAD

**Issue by giordano** [JuliaAstro/Cosmology.jl#26]
Docstrings can be adapted from the `README.md`

**Comment by mileslucas** [comment]
I’ve got this! (better than working on finals projects)

**Comment by mileslucas** [comment]
Closed via #29 

Just need to add the documenter keys to Travis/gh @giordano

**Comment by giordano** [comment]
I did already: https://juliaastro.github.io/Cosmology.jl/dev/ :wink:

**Comment by mileslucas** [comment]
Ah, one of the readme badges is pointing to the wrong url (latest instead of dev). Do you want to do a quick push to master? I’m away from my computer today.
