### ISSUE TITLE
bump UnitfulAstro to 1.0

### ISSUE THREAD

**Issue by xzackli** [JuliaAstro/Cosmology.jl#32]
Cosmology 1.0.x should have `[compat]` allowing `UnitfulAstro 1.0`, right? The semver 1.0 would imply that things could break -- is that why it hasn't yet been done?

**Comment by giordano** [comment]
> is that why it hasn't yet been done?

No, it's just that no one did it. Pull requests are welcome, maybe a pr to install compat helper here would be the best option, see https://github.com/JuliaAstro/LombScargle.jl/pull/14

**Comment by xzackli** [comment]
Wow, I didn't know you could install Actions via PR! I'll open one.

**Comment by giordano** [comment]
Fixed by #35
