### ISSUE TITLE
Unitful quantities: either reexport units or clarify docs?

### ISSUE THREAD

**Issue by stillyslalom** [JuliaAstro/Cosmology.jl#37]
ref. https://discourse.julialang.org/t/how-to-use-units-in-cosmology-jl/51935/2, this package includes several examples in its documentation which require Unitful and UnitfulAstro to run. Those requirements should either be made clear in the documentation, or the relevant parts of Unitful/UnitfulAstro should be re-exported from here.

**Comment by giordano** [comment]
I'm not personally happy about re-exporting stuff (even though I can see why it'd be useful here).  An improvement to documentation is definitely warranted.  Pull requests are welcome :slightly_smiling_face:
